version: '3.8' 
services: 
  web: 
    image: nginx:latest 
    ports: 
      - "8080:80" 
    volumes: 
      - .\html:C:\Users\sahaj\eclipse-workspace\OpencartV001\html 
    networks: 
      - webnet 
networks: 
  webnet: 
#refer session 54 of hybrid framework